import Navbar from "../components/Navbar";
import Head from "next/head";
import styles from "./Main.module.css";
import { FC } from "react";

interface MainLayoutProps {
  children: React.ReactNode;
}

const MainLayout = ({ children }:MainLayoutProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Alexander</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>{children}</main>
    </div>
  );
};

export default MainLayout;